accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('dashboard/',dashboard_view, name='dashboard'),
    path('profile/',edit_profile, name='edit_profile')
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('accounts/', include('accounts.urls')),
] 
if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path
from blogapp.views import *

app_name = 'blogapp'
urlpatterns = [
    path('', post_list, name='post_list'),
    path('category/<slug:category>/', post_list, name='category_post_list'),
    path('<slug:slug>/', post_detail, name='post_detail'),
    path('post_search/', post_search, name='post_search'),
    path('add/add/', add_post, name='add_post'),
    path('<slug:slug>/update/', post_update, name='post_update'),
    path('<slug:slug>/deleted/', post_delete, name='post_delete'),
    path('<int:post_id>/stream/', stream_view, name='stream_view'),
]

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(statut='published')


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_posts' , null=True)
    STATUTS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    body = models.TextField()
    image = models.ImageField(upload_to='', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    statut = models.CharField(choices=STATUTS_CHOICES, default='draft', max_length=10)
    publish = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE , related_name='posted')
    objects = models.Manager() #manager par defautf
    published = PublishedManager() #manager personnalisé

    def __str__(self):
        return self.title
    

class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    username = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.post.title

blogapp/forms.py
from django import forms
from blogapp.models import Comments, Post

class CommentsForm(forms.ModelForm):
  username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control' , 'placeholder': 'Nom d\'utilisateur'}))
  email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control' , 'placeholder': 'Email'}))
  body = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control' , 'placeholder': ' Votre commentaire'}))
  class Meta:
    model = Comments
    fields = ['username', 'email', 'body']
   

class SearchPost(forms.Form):
  query = forms.CharField(max_length=200,widget=forms.TextInput(attrs={'class': 'form-control' , 'placeholder': 'Search'}))

  class Meta:
    fields = ['query']
    
class PostForm(forms.ModelForm):
  
  title = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'form-control' , 'placeholder': 'Titre'}))
  body = forms.CharField(max_length=1000, widget=forms.Textarea(attrs={'class': 'form-control' , 'placeholder': 'Votre article'}))
  image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control' , 'placeholder': 'Image'}))
 
  class Meta:
    model = Post
    fields = ['title', 'body', 'image']

blogapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comments , Category
from django.core.paginator import (Paginator, EmptyPage, PageNotAnInteger)
from blogapp.forms import CommentsForm
from blogapp.forms import SearchPost, PostForm
from django.contrib.postgres.search import SearchVector
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth import get_user_model
import json
import time
from django.core.serializers.json import DjangoJSONEncoder
from django.http.response import HttpResponse, StreamingHttpResponse
# Create your views here.
def post_list(request, category=None,*args, **kwargs):
    now = timezone.now()
    posts = Post.published.all()
    categories = Category.objects.all()
    if category:
        category = get_object_or_404(Category, slug=category)
        posts = posts.filter(category=category)
    paginator = Paginator(posts, 2)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'posts': posts,
        'page': page,
        'categories': categories,
        'category': category,
        'now': now
    }
    return render(request, 'blog/post/liste.html',context)

def post_detail(request, slug : str):  
    
    User = get_user_model()
    superuser = User.objects.filter(is_superuser=True).first()
    suser = superuser.username
    categories = Category.objects.all()
    post = get_object_or_404(Post, slug=slug)
    comments = Comments.objects.filter(post=post.id)
    page = request.GET.get('page')
    paginator = Paginator(comments, 2)
    
    try:
        comment = paginator.page(page)
    except PageNotAnInteger:
        comment = paginator.page(1)
    except EmptyPage:
        comment = paginator.page(paginator.num_pages)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentsForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()

    else:
        comment_form = CommentsForm()
        
    context = {
        'post': post,
        'comments': comment,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'categories': categories,
        'superuser': suser
    }
        
    return render(request, 'blog/post/detail.html',context)


def post_search(request):
    query = None
    results = []
    search_form = SearchPost()
    if 'query' in request.GET:
        search_form = SearchPost(request.GET)
        if search_form.is_valid():
            query = search_form.cleaned_data['query']
            results = Post.published.annotate(search=SearchVector("title", "body")).filter(search=query)
           
    return render(request, 'blog/post/search.html', {
                'results': results,
                'query': query,
                'search_form': search_form
            })

def add_post(request):
    messages= ""
    if request.user.is_authenticated:
        if request.method=='POST':
            form = PostForm(request.POST, request.FILES)
            if form.is_valid():
                obj = form.save(commit=False)
                obj.author = request.user
                obj.save()
                messages = "Post créé avec succès , l'administrateur validera votre post dans les plus brefs délais"
                return render(request, 'blog/post/add.html', {'form': form , 'message': messages})
        else:
            form = PostForm()
            return render(request, 'blog/post/add.html', {'form': form })
    else:
        return redirect('accounts:login')
    
def post_update(request, slug : str, *args, **kwargs):
    post = get_object_or_404(Post, slug=slug)
    if request.user.is_authenticated:
        if post.author == request.user:
                if request.method=='POST':
                    form = PostForm(request.POST, request.FILES, instance=post)
                    if form.is_valid():
                        obj = form.save(commit=False)
                        obj.author = request.user
                        obj.save()
                        return redirect('blogapp:post_detail', slug=post.slug)
                else:
                    form = PostForm(instance=post)
                return render(request, 'blog/post/update.html', {'form': form})
        else:
            return redirect('blogapp:post_detail')
    else:
        return redirect('accounts:login')



def stream_view(request,post_id):
    def event_stream():
        initial_data = ''
        commments = commments.objects.filter(post_id=post_id)\
             .values('body', 'created', 'author__username', 'post__id')
        while True:
            data = json.dumps(list(commments.values()), cls=DjangoJSONEncoder)
            if not initial_data == data:
               yield '\n'
               yield f'data: {data}'
               yield '\n\n'
            time.sleep(1)
    return StreamingHttpResponse(event_stream(), content_type='text/event-stream')





def post_delete(request, slug : str, *args, **kwargs):
    messages= 'Votre post à été supprimé avec succès !'
    post = get_object_or_404(Post, slug=slug)
    if request.user.is_authenticated:
        if post.author == request.user:
            post.delete()
        return render(request, 'blog/post/delete.html', {'message': messages})
    else:
        return redirect('accounts:login')

blogapp/templates/blog/post/detail.html
{% extends 'base.html' %}
{% block title %}
 details de la publication
 {% endblock%}

 {% block content %}
   <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{post.title}}</h1>
                            <!-- Post meta content-->
                            <h3 class="text-muted fst-italic mb-2">Posté le {{post.publish}} ,  par {{post.author}}</h3>
                            <!-- Post categories-->
                            
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!"><em>IRIE DEV |</em> Developper fullstack</a>
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Designer web</a>
                            
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="{{post.image.url}}" alt="..." /></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{post.body}}</p>
                           
                        </section>
                          <button id="bu" class="btn btn-primary m-1" ><a href="{% url 'blogapp:post_list' %}" style="text-decoration: none; color: rgb(255, 255, 255) ; font-weight: bolder;"><span id="animbtn" class=" spinner-border-sm" aria-hidden="true"></span>Retour</a></button>
                          {% if post.author == request.user %}
                          <a href="{% url 'blogapp:post_update' post.slug %}" class="btn btn-outline-dark m-1" ><span id="animbtn" class=" spinner-border-sm" aria-hidden="true"></span>Modifier</a>
                          <a href="{% url 'blogapp:post_delete' post.slug %}" class="btn btn-outline-danger m-1" ><span id="animbtn" class=" spinner-border-sm" aria-hidden="true"></span>Supprimer</a>
                          {% else %}
                          <text class="text-danger text-muted">impossible de modifier ce post car vous n'êtes pas l'auteur</text>
                          {% endif %}
                    </article>
                    <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-body">
                            <div class="card-body">
                                <h2>
                                    
                                    {% with comments.count as total_comments %}
                                    {{total_comments}} comment{{total_comments | pluralize}}
                                        
                                    {% endwith %}
                                        
                                </h2>
                                
                                <!-- Comment form-->
                              
                                    
                                    {% if new_comment %}
                                        <h3>Ton commentaire a été posté avec succès</h3>
                                     {% else %}

                                     <h3>Poster un commentaire</h3>

                                    <form method="post" class="">
                                        {% csrf_token %}
                                        {{comment_form.as_p}}
                                      
                                        <button type="submit" class="btn btn-dark" value="Poster">Envoyer</button>
                                    </form>

                                    {% endif %}
                                        
                               
                              
                              <div class="comments">

                              </div>
                                <!-- Single comment-->
                                
                                {% for comments in comments %}
                                     <!-- Single comment-->
                                <div class="d-flex p-2">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="{{comments.post.image.url}}" height="36" width="36" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">
                                            {{forloop.count}}  {{comments.username}}
                                          <div class="text-muted fst-italic mb-2">
                                           à  {{comments.created}}
                                         </div>
                                         {{comments.body}}
                                    </div>
                                </div>
                                {% empty %}
                                <p>Pas de commentaires</p>
                                {% endfor %}
                                
                                  <!-- pagination -->
                        

                                <nav aria-label="Page navigation example">
                                  <ul class="pagination">
                                    {% if comments.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?page={{comments.previous_page_number}}">Précédent</a></li>
                                   {% endif %}
                                    <li class="page-item"><a class="page-link" href="#">{{comments.number}}</a></li>
                                    <li class="page-item active"><a class="page-link" href="#">of</a></li>
                                    <li class="page-item"><a class="page-link" href="#">{{comments.paginator.num_pages}}</a></li>
                                    {% if comments.has_next %}
                                   <li class="page-item"><a class="page-link" href="?page={{comments.next_page_number}}">Suivant</a></li>
                                   {% endif %}
                                  </ul>
                                </nav>


                        <!-- pagination end -->

                            </div>
                        </div>
                    </section>
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <!-- <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-dark" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div> -->
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                {% for cat in categories %}
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a class="text-capitalize text-danger fw-bolder fst-italic" href="{% url 'blogapp:category_post_list' cat.slug %}">{{cat.name}}</a></li>
                                    </ul>
                                </div>                                    
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card text-bg-dark">
                   <div class="card-header">INFO :</div>
                   <div class="card-body">
                     <h5 class="card-title">Pour toutes Publicités sur IRIE-BLOG cliquez sur le boutton ci-dessous</h5>
                    <a href=" https://wa.me/+22559444725"><button class="btn btn-success" >whatsapp</button></a> 
                   </div>
                   </div>
                </div>
            </div>
        </div>
   
  <script>
  document.getElementById("bu").addEventListener("click", function () {
    document.getElementById("animbtn").classList.add("spinner-border");
    setTimeout(function () {
      document.getElementById("animbtn").classList.remove("spinner-border");
    }, 500);
  });
  </script>
  
{% endblock %}
 
{% block DomReady %}
<script>
//   document.addEventListener("DOMContentLoaded", function(event) {
//     const eventSource = new EventSource("/stream/{{post.id}}");
//     eventSource.onmessage = function(event) {
//       const data = JSON.parse(event.data);
//       console.log(data);
//       document.getElementById("comments").innerHTML = data.body;
//     };
//   });
  let = eventSource = new EventSource("{% url 'blogapp:stream_view' post.id %}");
eventSource.onopen = function(event) {
  console.log("ouverture de la connexion");
};

eventSource.onmessage = function(event) {
const resp =JSON.parse(event.data);
if(resp?.length < 0){
  content = "<h2>Aucun commentaire</h2>";
}else {
    resp?.map(function(item, index) {
      content += Buildcontent(index+1, item['author_uername'], item['body'], 
      item['created']);
      
    });
}
document.querySelector(".comment").innerHTML = content;
console.log(resp);
};

eventSource.onerror = function(event) {
  console.log(event);
};

function Buildcontent (index,){
    const content = `  <div class="d-flex p-2">
              <div class="flex-shrink-0"><img class="rounded-circle" src="{{comments.post.image.url}}" height="36" width="36" alt="..." /></div>
              <div class="ms-3">
                  <div class="fw-bold">
                      #${{index}}  ${{author}}
                     <div class="text-muted fst-italic mb-2">
                      à  ${{created}}
                  </div>
                 {{comments.body}}
             </div>
         </div>`
         return content;
}

</script>
{% endblock DomReady %}

blogapp/templates/blog/post/liste.html
    
    
{% extends 'base.html' %}
{% load static %}
{% block title %}
 Liste des publication
 {% endblock %}


{% block content %}
 <script>
  document.getElementById("bu").addEventListener("click", function () {
    document.getElementById("animbtn").classList.add("spinner-border");
    setTimeout(function () {
      document.getElementById("animbtn").classList.remove("spinner-border");
    }, 500);
  });
  </script>
 <style>
    header {
        background-image: url("{% static 'images/blogg.jpg' %}");
        background-position:100%;
        
    }
</style>
    <header class="py-5 border-bottom mb-4" >
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder text-uppercase text-dark text-bg-light rounded-4">Bienvenue {{request.user.username | upper}} 🤩 sur IRIE-BLOG ! <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16"></svg>
                    <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783"/>
                    </svg></h1>
                    
                    {% if category %}
                        <h3 class="fw-semibold text">suivez la catégorie : {{ category }}</h3>
                    {% endif %}
                        
                </div>
            </div>
        </header>
        
         <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    <div class="card mb-4">
                        <a href="#!"><img class="card-img-top" src="{% static 'images/news.jpg' %}" alt="..." /></a>
                        <div class="card-body">
                            <h3 class=" text-muted">
                                {% if now %}
                                {{ now }}
                                {% endif %}
                               
                            </h3>
                            <h2 class="card-title small">Incrivez vous pour voir plus d'infos et restez informés sur les dernières nouvelles du pays !</h2>
                            {% if message %}
                            <div class="alert alert-success" role="alert">
                            <div>{{message}}</div>
                             <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                            {% endif %}
                            <p class="card-text"></p>
                            <button id="bu" class="btn " style="background-color:darkcyan ; "><a href="{% url 'accounts:register' %}" style="text-decoration: none; color: rgb(255, 255, 255) ; font-weight: bolder;"><span id="animbtn" class=" spinner-border-sm" aria-hidden="true"></span>Inscrivez vous</a></button>
                        </div>
                    </div>

                    


                    <!-- Nested row for non-featured blog posts-->
                    <div class="row">
                       
                       {% for post in posts %}
                         <div class="col-lg-6">
                            <!-- Blog post-->
                           
                            <!-- Blog post-->
                            <div class="card mb-4 bg-body-secondary">
                                
                                {% if  post.image %}
                                <a href="#!"><img class="card-img-top" src="{{post.image.url}}" alt="..." /></a>
                                    {% else %}
                                <a href="#!"><img class="card-img-top" src="" alt="image" /></a>

                                {% endif %}
                                    
                                <div class="card-body">
                                    <div class="small text-muted">{{post.publish}}</div>
                                    <h2 class="card-title h4">{{post.title}}</h2>
                                    <p class="card-text">{{ post.body | truncatechars:50 }}</p>
                                    <button id="bu" class="btn" style="background-color:darkcyan ; "><a href="{% url 'blogapp:post_detail' post.slug %}" style="text-decoration: none; color: rgb(255, 255, 255) ; font-weight: bolder;"><span id="animbtn" class=" spinner-border-sm" aria-hidden="true"></span>Lire plus...</a></button>
                                </div>
                            </div>
                        </div>
                       {% endfor %}
                        
                       
                    </div>
                    <!-- Pagination-->
             {% include 'blog/layouts/paginator.html' with page=posts %}
                    <!-- <nav aria-label="Pagination">
                        <hr class="my-0" />
                        <ul class="pagination justify-content-center my-4">
                            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>
                            <li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>
                            <li class="page-item"><a class="page-link" href="#!">2</a></li>
                            <li class="page-item"><a class="page-link" href="#!">3</a></li>
                            <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
                            <li class="page-item"><a class="page-link" href="#!">15</a></li>
                            <li class="page-item"><a class="page-link" href="#!">Older</a></li>
                        </ul>
                    </nav> -->
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Champs de recherche</div>
                        <div class="card-body">
                            <form method="get"  action="{% url 'blogapp:post_search' %}" >
                                <input class="form-control" name="query" type="search" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-dark m-1" id="button-search" type="submit">rechercher</button>
                            </form>

                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories de publication</div>
                        <div class="card-body">
                            <div class="row">
                                
                                {% for cat in categories %}
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a class="text-capitalize text-danger fw-bolder fst-italic" href="{% url 'blogapp:category_post_list' cat.slug %}">{{cat.name}}</a></li>
                                    </ul>
                                </div>                                    
                                {% endfor %}
                                    

                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                   <div class="card text-bg-dark">
                   <div class="card-header">INFO :</div>
                   <div class="card-body">
                     <h5 class="card-title">Pour toutes Publicités sur IRIE-BLOG cliquez sur le boutton ci-dessous</h5>
                    <a href=" https://wa.me/+22559444725"><button class="btn btn-success" >whatsapp</button></a> 
                   </div>
                   </div>
                </div>
            </div>
        </div>



  
{% endblock %}

blogapp/templates/blog/post/search.html
{% extends 'base.html' %}

{% block title %}
 recherche
 {% endblock%}

 {% block content %}
  
 <div class="container column">
    {% if query %}

    <h1>Résultats de la recherche pour "{{query}}"</h1>
    <h3>
        {% with results.count as total_results %}
               trouvé  {{total_results}} résultat{{total_results | pluralize}}
        {% endwith %}
    </h3>

    {% for post in results %}
        <div class="col-lg-6">
             <!-- Blog post-->           
             <!-- Blog post-->
            <div class="card mb-4">
                <a href="#!"><img class="card-img-top" src="{{post.image.url}}" alt="..." /></a>
                <div class="card-body">
                    <div class="small text-muted">{{post.publish}}</div>
                     <h2 class="card-title h4">{{post.title}}</h2>
                     <p class="card-text">{{ post.body | truncatechars:50 }}</p>
                     <button id="bu" class="btn" style="background-color:darkcyan ; "><a href="{% url 'blogapp:post_detail' post.slug %}" style="text-decoration: none; color: rgb(255, 255, 255) ; font-weight: bolder;"><span id="animbtn" class=" spinner-border-sm" aria-hidden="true"></span>Lire plus...</a></button>
                     <button id="bu" class="btn btn-secondary" ><a href="{% url 'blogapp:post_list' %} " class="text-dark" ><span id="animbtn" class=" spinner-border-sm" aria-hidden="true"></span>Retour</a></button>
                </div>
             </div>
        </div>
         {% empty %}
        <p>Aucun résultat</p>
        {% endfor %}
       
        {% else %}
         
        <h1>Recherche</h1>
        <form  method="get" action="{% url 'blogapp:post_search' %}">
           {% csrf_token %}
           {{ search_form.as_p }}
            <button type="submit" class="btn btn-dark">Rechercher</button>
        </form>
    {% endif %}

 </div>
    
{% endblock %}